id: I684AF97B
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T13:19:36+00:00'
last_modified: '2022-06-08T08:59:05.460456+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1AC413
  title: དངུལ་ཆུ་བཙོ་བཀྲུ་ཆེན་མོ་དང་ལྕགས་ཁམས་ཐལ་བཟོ་སོགས་ཀྱི་ལག་ལེན་ཕྱོགས་བསྒྲིགས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    EC40:
      image_group_id: I2PD17796
      title: ''
      total_pages: 560
      order: 1
      base_file: EC40.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
