id: P009151
initial_creation_type: ocr
source_metadata:
  id: bdr:W1AC413
  title: དངུལ་ཆུ་བཙོ་བཀྲུ་ཆེན་མོ་དང་ལྕགས་ཁམས་ཐལ་བཟོ་སོགས་ཀྱི་ལག་ལེན་ཕྱོགས་བསྒྲིགས།
  author: ''
  volumes:
    45c73336782f41a087fab0cc5214b97d:
      image_group_id: I2PD17796
      title: ''
      volume_number: 1
      total_pages: 560
